# Netlify Configuration
[build]
  publish = "web"
  command = "echo 'Static site, no build needed'"

# Redirects for SPA
[[redirects]]
  from = "/api/*"
  to = "https://chatcpt-api.vercel.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://chatcpt-api.vercel.app https://qaepmzfqzpawaqktjrlw.supabase.co;"

# Environment variables (for build)
[build.environment]
  NODE_VERSION = "18"