# Cloudflare Workers Configuration
name = "chatcpt-api"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# Environment Variables
[env.production.vars]
ENVIRONMENT = "production"

# KV Namespaces (for caching)
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# Durable Objects (for real-time features)
[[durable_objects.bindings]]
name = "CHAT_ROOMS"
class_name = "ChatRoom"

# Routes
[env.production]
routes = [
  { pattern = "api.chatcpt.com/*", zone_name = "chatcpt.com" }
]

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Compatibility flags
compatibility_flags = ["nodejs_compat"]